### ISSUE TITLE
What is the difference between yPos (xPos) and PositionY (PositionX)?

### ISSUE THREAD

**Issue by Ra1nWarden** [ijt3cd/4730#12]
I found these two fields in `DisplayObject` and one of them is `float` while the other is `int`. Are they designed for different purposes?

**Comment by AlexBailey20** [comment]
The PositionX and PositionY handle non integer values of positions that result from the physics while xPos and yPos are values that give where the sprite should be drawn. xPos and yPos are set to (int) PositionX and PositionY as one of the last parts of the update loop. It's a little unnecessary

**Comment by Ra1nWarden** [comment]
I will refactor this using floating point only if you are ok with it.

**Comment by AlexBailey20** [comment]
Yeah that makes more sense. The int version is really only needed in one place and is derived directly from the float values

**Comment by Ra1nWarden** [comment]
Done. 5fa986c537078dc7a22366dabe9d33cb778df1d4
