### ISSUE TITLE
Gem powerups

### ISSUE THREAD

**Issue by AlexBailey20** [ijt3cd/4730#15]
Collecting gems give a new interaction with the ghost (reverse, slow ghost, etc.)

**Comment by AlexBailey20** [comment]
Also can add player powerups such as super jump, double jump. Indicated by graphic which gives player idea of power up. All power ups are controlled by the same button

**Comment by Ra1nWarden** [comment]
Reverse ghost is done. Slower ghost is next on the list.

**Comment by Ra1nWarden** [comment]
After picking up a powerup, holding a button slows the ghost.

**Comment by Ra1nWarden** [comment]
I am not sure how to demonstrate the slowing down power up in a level. I feel there is nothing that can only be solved by a slowed down ghost. How about making this a feature? Such that the player can always hold down B to slow down the ghost at any time? What do you guys think?

**Comment by Ra1nWarden** [comment]
Slowing ghost is now part of the controls of the game.
