### ISSUE TITLE
Refactor out a TiledGame class

### ISSUE THREAD

**Issue by Ra1nWarden** [ijt3cd/4730#27]
There are many duplication in the classes for the Levels. I am planning to refactor out a `TiledGame` class that loads the map and creates the platforms, sprites, etc. This would make the code cleaner and more agile.

**Comment by ijt3cd** [comment]
My thought on this was to make it a class with the tmx file as the parameter for the constructor- then just have a switch statement in the level-complete code that determines next load based on current level

**Comment by Ra1nWarden** [comment]
That would work too. Then we just have one class with many tmx files as levels.

**Comment by Ra1nWarden** [comment]
Done 97358407a152c1cbec2eccbf0169c743ea100abd
Thanks!
