### ISSUE TITLE
Some questions about the design of the engine

### ISSUE THREAD

**Issue by Ra1nWarden** [ijt3cd/4730#3]
- When I was reading the code, I was wondering why the control of megaman was coded in the `LabGame` class. My understanding was that the control could be done much higher up in say `DisplayObject` such that all sub-classes get the same logic.
- Also, the movement of the sprites was kind of confusing. There are some for gravity coded in the `AnimatedSprite` class and the `Game` class also controls the speed of it. What was the purpose for this?
- Do we need `dx` and `dy` for speed? As I thought the game is like super mario and the inertia is almost negligible?

Sorry for any misunderstanding. The design was very different from what I did (which is nowhere near being good either) and I am curious about your thoughts.

**Comment by AlexBailey20** [comment]
I don't know what we want to do moving forward, but the dx and dy seem to be causing issues for the prototype so since we are short on time I'm going to make the movement more linear and we can figure out more complex movement for the alpha on Friday.

**Comment by Ra1nWarden** [comment]
Sounds good.
