### ISSUE TITLE
Death count and par fonts.

### ISSUE THREAD

**Issue by Ra1nWarden** [ijt3cd/4730#32]
Top left corner for all levels. A better font for displaying these.

**Comment by ijt3cd** [comment]
Level Name: par, high
level8.tmx: 0, 0
level1.tmx: 1, 1
level10.tmx: 1, 1
level3.tmx: 1, 1
level9.tmx: 1, 1
level2.tmx: 2, 1
leveltest.tmx: 3, 2
level5.tmx: 1, 1
level6.tmx: 1, 1
big_level2.tmx: 8, 6? haven't beat it
big_level1.tmx: 7, 6
