### ISSUE TITLE
Frame rate

### ISSUE THREAD

**Issue by AlexBailey20** [ijt3cd/4730#4]
How is the game running on your systems? On mine it is not smooth at all. Megaman seems to move in chunks, especially in the y direction, even in the first commit.

**Comment by Ra1nWarden** [comment]
It is slow in my computer as well. My engine was slow too.
By the way, where is the random encounter that we are supposed to do by tonight?

**Comment by AlexBailey20** [comment]
Alright well for the prototype I'm thinking I'll use my engine just because it runs a bit smoother but long term we should see what we can do to fix that. The random encounter is in the Tests and Quizzes in Collab

**Comment by Ra1nWarden** [comment]
Sure. Thanks!
